"""Every way this product is installed, declared once.

`distributions/` held nineteen files at 0.2.0: eleven READMEs, four one-line
requirements files, two small JSON, two with content. A distribution matrix
whose rows are READMEs describing what a distribution would contain is a label
for a distribution matrix.

The lesson this repository has already learned three times — hand-maintained
exclusion lists, version literals in ten files, plugin trees generated by a
script nothing ran — applies here with more force, because a distribution
manifest is read by somebody else's installer. A plugin id that disagrees with
the npm name that disagrees with the MCP server name does not fail a test; it
fails for a user, once, at install, with no diagnostic.

So this module is the only place a target is described, and
`scripts/build_distributions.py` writes every manifest from it. Adding a
distribution means adding a row here. Editing a generated manifest by hand is
undone on the next build, exactly as it is under `plugins/`.

**Two statuses, and the difference is not cosmetic.**

``shipped``  the artifact in this repository is the thing that installs. A
             reader can run the command in ``install`` and have it working.
``external`` the artifact is complete and correct, and publication is a
             platform action this repository cannot perform — a marketplace
             review, an app submission. The manifest is real; the listing is
             not ours to claim.

There is no third status for "planned". A target with no artifact does not get
a row, it goes in ROADMAP.md with no implementation hints. A row here is a
promise that a file exists and works.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from .. import __version__

#: Canonical identity. Every generated manifest derives its names from these,
#: so the plugin id, the package name and the MCP server name cannot drift.
PRODUCT = "Maxey0-SuperSpace"
SHORT = "Maxey0"
MCP_NAMESPACE = "maxey0-ss"
DISTRIBUTION_ID = "maxey0"
PYTHON_PACKAGE = "maxey0_ss"
HOMEPAGE = "https://maxey0.com"
REPOSITORY = "https://github.com/mmc7676/Maxey0"
LICENSE = "Apache-2.0"
AUTHOR = {"name": "mmc7676", "url": "https://github.com/mmc7676"}

#: The deployed remote surface.
#:
#: `mcp.maxey0.com` is the production endpoint: a Cloudflare Worker edge
#: attached to the `maxey0.com` zone as a Custom Domain (see
#: `workers/mcp-edge/wrangler.jsonc`), fronting a Python origin over a
#: Cloudflare Tunnel. It resolves, and the edge serves the full 2026-07-28
#: metadata surface. Tool execution reaches the origin only while that origin
#: is up — it is a laptop process, so when it is down the host still resolves
#: and metadata still answers but `tools/call` returns -32011 / 502.
#:
#: Attaching the Custom Domain is what retired `maxey0-ss-mcp.maxey0.workers.dev`:
#: Cloudflare disables the workers.dev route once a custom domain is attached,
#: so that name now returns HTTP 404 on every path. A connector manifest naming
#: it fails at install with a 404 and no diagnostic, which is why the host is
#: declared once, here, and every manifest is derived from it.
REMOTE_MCP_HOST = "mcp.maxey0.com"
REMOTE_MCP_URL = f"https://{REMOTE_MCP_HOST}/mcp"

MCP_PROTOCOL = "2026-07-28"

ONE_LINE = (
    "Governed context and execution for agents: an explicit SCW address space, "
    "a gate at every tool call and every model egress, and a hash-chained "
    "record of both."
)


@dataclass(frozen=True)
class Target:
    """One installable thing, and what a user does to get it."""

    #: Stable identifier. Directory name under `distributions/`.
    id: str
    #: What a human calls it.
    title: str
    #: Which vendor's surface this installs into.
    platform: str
    #: "plugin" | "connector" | "app" | "skills" | "harness" | "sdk" | "server"
    kind: str
    status: str
    #: What the user runs or does.
    install: str
    #: Repo-relative paths that make up the artifact. Every one must exist.
    artifacts: tuple[str, ...] = ()
    #: Generated file -> content builder name in `builders`.
    generates: tuple[str, ...] = ()
    #: Optional python dependency, never vendored.
    optional_dependency: str = ""
    notes: str = ""
    extra: dict[str, Any] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Anthropic surfaces
# ---------------------------------------------------------------------------

CLAUDE_CODE_PLUGIN = Target(
    id="claude-code-plugin",
    title=f"{SHORT} for Claude Code",
    platform="claude-code",
    kind="plugin",
    status="shipped",
    install="/plugin marketplace add mmc7676/Maxey0\n/plugin install maxey0@maxey0",
    artifacts=(
        ".claude-plugin/marketplace.json",
        "plugins/maxey0/.claude-plugin/plugin.json",
    ),
    generates=("distributions/claude-code-plugin/README.md",),
    notes=(
        "The plugin directories under plugins/ are generated from the "
        "repository root by scripts/build_planes.py, and packaging refuses to "
        "run if they have drifted."
    ),
)

def _plane_plugin(plane: str, title: str, summary: str) -> Target:
    """One of the four plugins the marketplace ships beside the full stack.

    The marketplace offered five installable plugins while this registry
    declared one, so `DISTRIBUTION_MATRIX.md` showed a reader a single Claude
    Code plugin and `/plugin marketplace add` offered five. A registry whose
    docstring says it is "the only place a target is described" has to actually
    be that, or it is a fourth list.
    """
    plugin = f"maxey0-{plane}"
    return Target(
        id=f"claude-code-{plane}",
        title=title,
        platform="claude-code",
        kind="plugin",
        status="shipped",
        install=(
            "/plugin marketplace add mmc7676/Maxey0\n"
            f"/plugin install {plugin}@maxey0"
        ),
        artifacts=(f"plugins/{plugin}/.claude-plugin/plugin.json",),
        generates=(f"distributions/claude-code-{plane}/README.md",),
        notes=summary,
    )


CLAUDE_CODE_CONTEXT = _plane_plugin(
    "context", f"{SHORT} Context plane",
    "The window and the only writer of it, installable alone. No loop library "
    "and no Gate.")
CLAUDE_CODE_LOOPS = _plane_plugin(
    "loops", f"{SHORT} Loop plane",
    "Routing and the formation library, installable alone. Holds no window "
    "state at all, which is what lets it run against a fixed context scheme.")
CLAUDE_CODE_OBSERVE = _plane_plugin(
    "observe", f"{SHORT} Observatory plane",
    "The Gate, the evidence and the Studio, installable alone. Installs inert: "
    "the default mode records and blocks nothing.")
CLAUDE_CODE_LAB = _plane_plugin(
    "lab", f"{SHORT} lab",
    "The experiment harness. Research tooling and explicitly not part of the "
    "product -- install it only if you are running a study. Nothing in the "
    "three planes depends on it.")

CLAUDE_DESKTOP_CONNECTOR = Target(
    id="claude-desktop-connector",
    title=f"{SHORT} for Claude Desktop",
    platform="claude-desktop",
    kind="connector",
    status="shipped",
    install=f"Drag dist/maxey0-{__version__}.mcpb into Claude Desktop.",
    artifacts=("manifest.json",),
    generates=(
        "distributions/claude-desktop-connector/README.md",
        "distributions/claude-desktop-connector/connector.json",
    ),
    notes=(
        "The manifest declares the UV runtime, so Claude Desktop provisions "
        "Python and every dependency itself. The .dxt is the same bytes under "
        "the former extension."
    ),
)

CLAUDE_SKILLS = Target(
    id="claude-skills",
    title=f"{SHORT} skills",
    platform="claude",
    kind="skills",
    status="shipped",
    install="Included in the Claude Code plugin; copy skills/ to use them alone.",
    artifacts=("skills/",),
    generates=("distributions/claude-skills/README.md",),
)

CLAUDE_REMOTE_CONNECTOR = Target(
    id="claude-remote-connector",
    title=f"{SHORT} remote MCP connector",
    platform="claude",
    kind="connector",
    status="external",
    install=f"Add {REMOTE_MCP_URL} as a custom connector.",
    generates=(
        "distributions/claude-remote-connector/README.md",
        "distributions/claude-remote-connector/connector.json",
    ),
    notes=(
        "The endpoint answers MCP 2026-07-28 and the manifest is complete. "
        "Directory listing is a platform action and is not claimed here."
    ),
)

# ---------------------------------------------------------------------------
# OpenAI surfaces
# ---------------------------------------------------------------------------

CHATGPT_APP = Target(
    id="chatgpt-app",
    title=f"{SHORT} for ChatGPT",
    platform="chatgpt",
    kind="app",
    status="external",
    install=f"Settings → Connectors → Add: {REMOTE_MCP_URL}",
    generates=(
        "distributions/chatgpt-app/README.md",
        "distributions/chatgpt-app/app.json",
        "distributions/chatgpt-app/openai-connector.json",
    ),
    notes=(
        "A ChatGPT app is an MCP server plus a manifest; both are here. "
        "Submission and review are OpenAI's and are not claimed here."
    ),
)

CODEX_PLUGIN = Target(
    id="codex",
    title=f"{SHORT} for Codex",
    platform="codex",
    kind="plugin",
    status="shipped",
    install="Append distributions/codex/config.toml to ~/.codex/config.toml",
    generates=(
        "distributions/codex/README.md",
        "distributions/codex/config.toml",
        "distributions/codex/AGENTS.md",
    ),
    notes=(
        "Codex reads MCP servers from ~/.codex/config.toml. The generated "
        "fragment names the stdio entry point in this repository."
    ),
)

# ---------------------------------------------------------------------------
# Protocol surfaces
# ---------------------------------------------------------------------------

MCP_STDIO = Target(
    id="mcp-stdio",
    title=f"{PRODUCT} MCP server (stdio)",
    platform="mcp",
    kind="server",
    status="shipped",
    install=f"python -m {PYTHON_PACKAGE}.mcp_stdio_server",
    artifacts=(f"{PYTHON_PACKAGE}/mcp_stdio_server.py",),
    generates=("distributions/mcp-stdio/README.md", "distributions/mcp-stdio/mcp.json"),
)

MCP_HTTP = Target(
    id="mcp-http",
    title=f"{PRODUCT} MCP server (Streamable HTTP)",
    platform="mcp",
    kind="server",
    status="shipped",
    # The console script, not `python -m ...mcp_public_server`: that module
    # builds a router and has no entry point, so the old command exited
    # without serving.
    install="maxey0-ss-public",
    artifacts=(f"{PYTHON_PACKAGE}/mcp_public_server.py", "workers/mcp-edge/src/index.ts"),
    generates=("distributions/mcp-http/README.md", "distributions/mcp-http/mcp.json"),
)

A2A_AGENT = Target(
    id="a2a",
    title=f"{PRODUCT} A2A agent",
    platform="a2a",
    kind="server",
    status="shipped",
    install="maxey0-ss-public",
    artifacts=(f"{PYTHON_PACKAGE}/a2a_server.py",),
    generates=("distributions/a2a/README.md", "distributions/a2a/agent-card.json"),
    notes=("The A2A endpoint is POST /v1/a2a/message on maxey0-ss-public; the "
           "agent card is served at /.well-known/agent-card.json."),
)

# ---------------------------------------------------------------------------
# Harness adapters
# ---------------------------------------------------------------------------


def _harness(hid: str, title: str, module: str, dependency: str, notes: str) -> Target:
    return Target(
        id=hid,
        title=title,
        platform="harness",
        kind="harness",
        status="shipped",
        install=f'pip install "{DISTRIBUTION_ID}[{hid}]"',
        artifacts=(f"{PYTHON_PACKAGE}/adapters/harnesses/{module}.py",),
        generates=(
            f"distributions/harnesses/{hid}/README.md",
            f"distributions/harnesses/{hid}/requirements.txt",
        ),
        optional_dependency=dependency,
        notes=notes,
        extra={"module": module},
    )


HARNESSES = (
    _harness("claude-agent-sdk", "Claude Agent SDK", "claude_agent_sdk",
             "claude-agent-sdk",
             "The SDK stays the execution harness; this owns the window and the record."),
    _harness("openai-agents", "OpenAI Agents SDK", "openai_agents", "openai-agents",
             "The SDK stays the execution harness; this owns the window and the record."),
    _harness("langchain", "LangChain / LangGraph", "langchain", "langgraph",
             "Binds a LangGraph node to a window so its tool calls are attributed; "
             "langgraph pulls langchain-core."),
    _harness("google-adk", "Google Agent Development Kit", "google_adk",
             "google-adk",
             "Binds an ADK agent to a window; A2A messages carry the address."),
    _harness("microsoft", "Microsoft Agent Framework", "microsoft",
             "agent-framework",
             "Covers AutoGen and Semantic Kernel through the same binding."),
    _harness("nvidia", "NVIDIA NeMo Agent Toolkit", "nvidia", "nvidia-nat",
             "Binds a NeMo workflow to a window; NIM endpoints are ordinary egress."),
)

# ---------------------------------------------------------------------------
# Client SDKs
# ---------------------------------------------------------------------------

# Only the Python client earns a row. `status="shipped"` here means what the
# docstring says it means — "a reader can run the command in `install` and have
# it working" — and `sdks/python/maxey0_mcp_client.py` is a single importable
# module that does. The Go and TypeScript fixtures did not: with a real Go
# toolchain `go build ./...` fails (`sdks/go/src/main.go` is `package main`
# with no `func main`, and the directory is `.../src`, not an importable
# package), and the TypeScript fixture has no build output, no `main`/`exports`
# entry point, and names an npm dependency it never imports — a consumer who
# follows `install` gets a directory they cannot import. Both call themselves
# "reference transport fixtures" in their own READMEs; carrying them as
# "shipped" was the overclaim. They remain on disk as fixtures and their
# capability is described, without shape, in docs/ROADMAP.md.
SDKS = (
    Target(id="sdk-python", title=f"{SHORT} MCP client (Python)", platform="sdk",
           kind="sdk", status="shipped", install="see sdks/python/",
           artifacts=("sdks/python/maxey0_mcp_client.py",),
           generates=("distributions/sdks/python/README.md",)),
)

TARGETS: tuple[Target, ...] = (
    CLAUDE_CODE_PLUGIN,
    CLAUDE_CODE_CONTEXT,
    CLAUDE_CODE_LOOPS,
    CLAUDE_CODE_OBSERVE,
    CLAUDE_CODE_LAB,
    CLAUDE_DESKTOP_CONNECTOR,
    CLAUDE_SKILLS,
    CLAUDE_REMOTE_CONNECTOR,
    CHATGPT_APP,
    CODEX_PLUGIN,
    MCP_STDIO,
    MCP_HTTP,
    A2A_AGENT,
    *HARNESSES,
    *SDKS,
)

BY_ID = {t.id: t for t in TARGETS}
BY_PLATFORM: dict[str, list[Target]] = {}
for _t in TARGETS:
    BY_PLATFORM.setdefault(_t.platform, []).append(_t)


def public_manifest() -> dict[str, Any]:
    """What `maxey0-ss.distribution` reports. Derived, never written down."""
    return {
        "product": PRODUCT,
        "version": __version__,
        "mcp_protocol": MCP_PROTOCOL,
        "planes": ["context", "execution", "engineering-observation"],
        "protocols": ["MCP " + MCP_PROTOCOL, "A2A"],
        "scw": "enforceable-address-space",
        "targets": [
            {
                "id": t.id,
                "title": t.title,
                "platform": t.platform,
                "kind": t.kind,
                "status": t.status,
                "install": t.install,
                "optional_dependency": t.optional_dependency or None,
            }
            for t in TARGETS
        ],
        "platforms": sorted(BY_PLATFORM),
        "harnesses": [t.id for t in HARNESSES],
        "remote_mcp": REMOTE_MCP_URL,
    }
