"""Context-plane tools that were declared outside the vendored runtime.

The four containment assertions and the Concept-window builder live here rather
than in `server/vendor/scw_runtime/`, because the vendored tree is generated by
`scripts/sync_vendor.py` and must never be hand-edited. They belong to the
Context plane for one reason: each one touches the live window, and the window
is process-local state.

The assertions are the sharpest thing in the product, so it is worth being
precise about what separates them. `context_assert_scope_closed` and
`context_assert_disjoint` are pure computations over the region graph — they
report `evidence.pure: true` and prove a property of a data structure.
`context_assert_can_read` and `context_assert_cannot_read` perform a **real
read through the real authorization path**: a refusal is produced by the
enforcement layer, lands in the ledger as a `scw.denied` record, and replay
reproduces it. "The closure does not contain region Y" and "role X asked for
region Y and the runtime refused, here is the event" are different claims, and
only the second one is evidence about the system.
"""

from __future__ import annotations

from typing import Optional

from . import bootstrap

bootstrap.prepare()

import concept_scw as cscw
from scw_runtime import partition
from scw_runtime.errors import SCWError
from scw_runtime.server import _session, _tool

def _closure_snapshot(loop_id: str) -> dict:
    window = _session.window
    return {
        "read_closure": sorted(window.read_closure(loop_id)),
        "write_closure": sorted(window.write_closure(loop_id)),
    }


def _events_since(seq: int) -> list[dict]:
    """Records appended since `seq`, as evidence for what an assertion did."""
    return [
        {"seq": r.get("seq"), "type": r.get("type"), "actor": r.get("actor"),
         "payload": r.get("payload")}
        for r in _session.window.log.records
        if (r.get("seq") or 0) >= seq
    ]


@_tool
def assert_can_read(loop_id: str, scw_id: str) -> dict:
    """Assert a bound role CAN read a region, by actually reading it.

    Performs a real `read` through the role's own scope. The assertion holds
    only if the runtime authorized it; a refusal means the role's partition is
    narrower than expected, and the refusal's own message and hint are
    returned rather than summarized.
    """
    window = _session.window
    if loop_id not in window.loops:
        return {"ok": False, "error": "unknown_loop", "loop_id": loop_id,
                "message": f"no loop {loop_id!r} is bound in this window"}
    mark = window.log.next_seq
    try:
        window.read(scw_id, loop_id=loop_id, include_children=False)
    except SCWError as exc:
        return {
            "assertion": "can_read", "loop_id": loop_id, "scw_id": scw_id,
            "holds": False,
            "observed": "refused",
            "refusal": exc.to_dict(),
            "closure": _closure_snapshot(loop_id),
            "evidence": {"pure": False, "events": _events_since(mark)},
            "note": "the runtime refused a read this assertion expected to "
                    "succeed; the role's scope is narrower than assumed",
        }
    return {
        "assertion": "can_read", "loop_id": loop_id, "scw_id": scw_id,
        "holds": True,
        "observed": "authorized",
        "closure": _closure_snapshot(loop_id),
        "evidence": {"pure": False, "events": _events_since(mark)},
    }


@_tool
def assert_cannot_read(loop_id: str, scw_id: str) -> dict:
    """Assert a bound role CANNOT read a region, by actually attempting it.

    This is the containment test. It makes a real read attempt and expects the
    runtime to refuse; the refusal is recorded as a `scw.denied` event that the
    audit chain covers and replay reproduces.

    If the read SUCCEEDS, the assertion fails and that is a containment breach,
    not a soft negative -- `breach` is set and the content that came back is
    reported as reachable. A breach is a headline finding.
    """
    window = _session.window
    if loop_id not in window.loops:
        return {"ok": False, "error": "unknown_loop", "loop_id": loop_id,
                "message": f"no loop {loop_id!r} is bound in this window"}
    if scw_id not in window.regions:
        return {"ok": False, "error": "unknown_region", "scw_id": scw_id,
                "message": f"no region {scw_id!r} exists; a read of a region "
                           f"that does not exist proves nothing about scope"}
    mark = window.log.next_seq
    try:
        result = window.read(scw_id, loop_id=loop_id, include_children=False)
    except SCWError as exc:
        return {
            "assertion": "cannot_read", "loop_id": loop_id, "scw_id": scw_id,
            "holds": True,
            "observed": "refused",
            "breach": False,
            "refusal": exc.to_dict(),
            "closure": _closure_snapshot(loop_id),
            "evidence": {"pure": False, "events": _events_since(mark)},
        }
    return {
        "assertion": "cannot_read", "loop_id": loop_id, "scw_id": scw_id,
        "holds": False,
        "observed": "authorized",
        "breach": True,
        "reachable_tokens": result.get("tokens"),
        "closure": _closure_snapshot(loop_id),
        "evidence": {"pure": False, "events": _events_since(mark)},
        "note": "CONTAINMENT BREACH: the runtime authorized a read this "
                "assertion expected it to refuse. Lead with this.",
    }


@_tool
def assert_scope_closed(
    loop_id: str,
    expected_read: Optional[list[str]] = None,
    expected_write: Optional[list[str]] = None,
) -> dict:
    """Assert a role's reachable set is exactly what was declared.

    Two modes, because "closed" means two useful things.

    With `expected_read` / `expected_write`: the closure must equal the sets
    given. Anything reachable that was not declared is `unexpected`; anything
    declared that is not reachable is `missing`.

    With neither: the scope is closed if nothing widens it beyond the role's
    own partition -- that is, no open bridge is currently extending its reach.
    `widened_by_grants` names whatever does.

    Pure: computed over the live region graph, mutating nothing and writing no
    event. `evidence.pure` says so, because a set computation is weaker
    evidence than an attempt the runtime actually refused.
    """
    window = _session.window
    loop = window.loops.get(loop_id)
    if loop is None:
        return {"ok": False, "error": "unknown_loop", "loop_id": loop_id,
                "message": f"no loop {loop_id!r} is bound in this window"}

    reads = set(window.read_closure(loop_id))
    writes = set(window.write_closure(loop_id))
    own = set(partition.own_reachable(window, loop))
    widened = sorted(reads - own)

    out: dict = {
        "assertion": "scope_closed", "loop_id": loop_id,
        "read_closure": sorted(reads), "write_closure": sorted(writes),
        "own_partition": sorted(own),
        "widened_by_grants": widened,
        "evidence": {"pure": True, "events": []},
    }

    if expected_read is None and expected_write is None:
        out.update({
            "mode": "no_open_grants",
            "holds": not widened,
            "note": ("an open bridge is extending this role's reach beyond its "
                     "own partition" if widened else
                     "nothing widens this role beyond its own partition"),
        })
        return out

    unexpected_r = sorted(reads - set(expected_read or []))
    missing_r = sorted(set(expected_read or []) - reads)
    unexpected_w = sorted(writes - set(expected_write or []))
    missing_w = sorted(set(expected_write or []) - writes)
    checked_w = expected_write is not None

    out.update({
        "mode": "declared",
        "holds": not (unexpected_r or missing_r
                      or (checked_w and (unexpected_w or missing_w))),
        "read": {"unexpected": unexpected_r, "missing": missing_r},
        "write": ({"unexpected": unexpected_w, "missing": missing_w}
                  if checked_w else None),
    })
    return out


@_tool
def assert_disjoint(loop_a: str, loop_b: str) -> dict:
    """Assert two roles share no private working space.

    **Not** `read_closure(a) ∩ read_closure(b) = ∅`. That formulation is too
    strong, and shipping it meant this assertion failed the product's own
    maker/checker/judge formation: a checker is *supposed* to read the maker's
    published draft, and every role is supposed to read the concept's
    constitution. Reporting a correct partition as a breach trains an operator
    to ignore the assertion, which is worse than not having it.

    The claim that actually matters is:

        Private(a) ∩ Private(b) = ∅        must hold
        Admitted(a → b) ≠ ∅                is the point of the formation

    So an overlapping region is classified rather than counted:

    `private_overlap`
        A region neither role owns that is `bridgeable=False` — a working pad.
        Two roles reaching one pad is a containment breach and the only thing
        that fails this assertion.

    `shared_reference`
        A region no bound role can write. Both may read it; neither can put
        anything in it. A region nobody writes cannot carry state from one role
        to another, so it is shared context without being a channel.

    `admitted`
        A region one role writes and the other reads — a declared handoff. This
        is the formation working. Each entry names its writers, so an admission
        nobody declared is visible as an unexpected writer rather than hidden in
        an aggregate.

    The five-rule maker/judge report is included in both directions as
    supplementary evidence: "can these two reach the same bytes" and "would this
    one's verdict on that one be accepted" are different questions, and a
    verdict can be refused for reasons that have nothing to do with overlap.

    Pure: computed over the region graph, mutating nothing and writing no event.
    `evidence.pure` says so, because a set computation is weaker evidence than
    an attempt the runtime actually refused.
    """
    window = _session.window
    missing = [lid for lid in (loop_a, loop_b) if lid not in window.loops]
    if missing:
        return {"ok": False, "error": "unknown_loop", "missing": missing,
                "message": f"not bound in this window: {missing}"}
    if loop_a == loop_b:
        return {"ok": False, "error": "same_loop",
                "message": "a loop is not disjoint from itself; name two roles"}

    reads_a = set(window.read_closure(loop_a))
    reads_b = set(window.read_closure(loop_b))
    overlap = reads_a & reads_b

    # Who can put bytes into each region. A region with no writer cannot be a
    # channel between two roles, whatever either of them can read.
    writers: dict[str, list[str]] = {}
    for lid in window.loops:
        for scw_id in window.write_closure(lid):
            writers.setdefault(scw_id, []).append(lid)

    private_overlap, shared_reference, admitted = [], [], []
    for scw_id in sorted(overlap):
        region = window.regions.get(scw_id)
        bridgeable = bool(region.policy.bridgeable) if region else True
        who = sorted(writers.get(scw_id, []))

        # `bridgeable=False` means "unreachable from outside, full stop". If
        # two roles both reach one, at least one of them is outside it — and
        # the case that matters most is nesting: a role bound to a parent with
        # `descend` reaches every private pad beneath it. An earlier draft of
        # this excused a region that sat inside either role's own subtree,
        # which excused exactly that. There is no legitimate formation in which
        # two roles share private working space.
        if not bridgeable:
            private_overlap.append(scw_id)
        elif not who:
            shared_reference.append(scw_id)
        else:
            admitted.append({"region": scw_id, "written_by": who})

    return {
        "assertion": "disjoint", "loop_a": loop_a, "loop_b": loop_b,
        "holds": not private_overlap,
        "private_overlap": private_overlap,
        "shared_reference": shared_reference,
        "admitted": admitted,
        "overlap": sorted(overlap),
        "read_closure_a": sorted(reads_a),
        "read_closure_b": sorted(reads_b),
        "verdict_a_grades_b": window.disjointness(loop_b, loop_a),
        "verdict_b_grades_a": window.disjointness(loop_a, loop_b),
        "evidence": {"pure": True, "events": []},
        "note": ("two roles reach the same private pad; that is a containment "
                 "breach" if private_overlap else
                 "no private working space is shared; overlap is declared "
                 "handoffs and unwritable reference"),
    }


ADMIT_RULES = ("approve", "summarize", "redact", "reject")
_SUMMARY_CHARS = 280


def _entry_line(key: Optional[str], data: str) -> str:
    return data if key is None else f"{key}: {data}"


@_tool
def admit(
    from_role: str,
    to_role: str,
    from_region: str,
    to_region: str,
    rule: str,
    redact_keys: Optional[list[str]] = None,
) -> dict:
    """Gate an explicit content handoff from one role's region to another's.

    Ingress -- what a role may reach -- is enforced by scope and bridges.
    This is egress: the decision governing what actually crosses once reach
    already permits it. `to_region` must already be in `to_role`'s read
    closure and `from_role`'s write closure -- admission governs WHAT flows
    through a handoff that structurally exists, it does not mint new reach.

    `rule` is one of:
      approve    from_region's content crosses unchanged.
      summarize  each entry is deterministically truncated to
                 %(chars)d characters with a length marker -- never an
                 invented summary.
      redact     entries whose key is in `redact_keys` are dropped; the rest
                 cross unchanged.
      reject     nothing crosses.

    A real, authorized read of `from_region` happens under every rule,
    including reject -- the gate has to see what it is deciding about. Every
    outcome is recorded as a `promote` event tagged `payload.gate == "admit"`,
    which is the record `context_assert_admitted` looks for.
    """ % {"chars": _SUMMARY_CHARS}
    window = _session.window
    missing = [lid for lid in (from_role, to_role) if lid not in window.loops]
    if missing:
        return {"ok": False, "error": "unknown_loop", "missing": missing,
                "message": f"not bound in this window: {missing}"}
    if rule not in ADMIT_RULES:
        return {"ok": False, "error": "bad_rule", "rule": rule,
                "message": f"rule must be one of {ADMIT_RULES}"}
    if to_region not in window.read_closure(to_role):
        return {"ok": False, "error": "to_role_cannot_read_to_region",
                "to_role": to_role, "to_region": to_region,
                "message": f"{to_role!r} cannot read {to_region!r}; admitting "
                            "content there would not reach it"}

    try:
        window.read(from_region, loop_id=from_role, include_children=False)
    except SCWError as exc:
        return {"ok": False, "error": "cannot_read_from_region",
                "refusal": exc.to_dict()}

    region = window.regions.get(from_region)
    entries = list(region.entries) if region else []
    redact_keys = redact_keys or []
    crossed = 0
    lines: list[str] = []

    if rule == "approve":
        lines = [_entry_line(e.key, e.data) for e in entries]
        crossed = len(lines)
    elif rule == "redact":
        kept = [e for e in entries if e.key not in redact_keys]
        lines = [_entry_line(e.key, e.data) for e in kept]
        crossed = len(kept)
    elif rule == "summarize":
        for e in entries:
            body = e.data
            if len(body) > _SUMMARY_CHARS:
                body = body[:_SUMMARY_CHARS] + f"...[summarized: {len(e.data)} chars]"
            lines.append(_entry_line(e.key, body))
        crossed = len(lines)
    # rule == "reject": lines stays [], crossed stays 0

    if lines:
        window.write(to_region, "\n".join(lines), loop_id=from_role, mode="append")

    record = window.log.emit(
        "promote",
        actor=f"loop:{from_role}",
        payload={
            "gate": "admit",
            "rule": rule,
            "from_role": from_role,
            "to_role": to_role,
            "from_region": from_region,
            "to_region": to_region,
            "redact_keys": redact_keys,
            "entries_considered": len(entries),
            "entries_crossed": crossed,
        },
    )
    return {
        "admitted": rule != "reject",
        "rule": rule,
        "from_role": from_role, "to_role": to_role,
        "from_region": from_region, "to_region": to_region,
        "entries_considered": len(entries),
        "entries_crossed": crossed,
        "event": {"seq": record["seq"], "type": record["type"]},
    }


@_tool
def assert_admitted(from_role: str, to_role: str) -> dict:
    """Assert every region `to_role` can read that `from_role` writes has a
    recorded `context_admit` decision naming this pair.

    `context_assert_disjoint` classifies overlap structurally: a region one
    role writes and the other reads is `admitted` in principle, whether or
    not a `context_admit` call ever actually ran. This checks the dynamic
    fact -- scanning the ledger for a `promote` event tagged
    `payload.gate == "admit"` naming (from_role, to_role) for each region
    their write/read closures say could carry a handoff.

    A region with the structural reach but no recorded admission is an
    `unadmitted_region`: not on its own a breach -- it may hold nothing yet --
    but a containment claim should be able to name a recorded reason for
    every path capable of moving content between two roles, and this is the
    thing that finds a path with none.

    Pure: scans the closures and the ledger's already-recorded events, and
    attempts nothing new. `evidence.pure` says so, because a scan of history
    is a weaker claim than an attempt the runtime just performed.
    """
    window = _session.window
    missing = [lid for lid in (from_role, to_role) if lid not in window.loops]
    if missing:
        return {"ok": False, "error": "unknown_loop", "missing": missing,
                "message": f"not bound in this window: {missing}"}

    handoff_regions = sorted(
        set(window.write_closure(from_role)) & set(window.read_closure(to_role))
    )
    admissions = [
        r for r in window.log.records
        if r.get("type") == "promote"
        and (r.get("payload") or {}).get("gate") == "admit"
        and (r.get("payload") or {}).get("from_role") == from_role
        and (r.get("payload") or {}).get("to_role") == to_role
    ]
    admitted_regions = sorted({r["payload"]["to_region"] for r in admissions})
    unadmitted = sorted(set(handoff_regions) - set(admitted_regions))

    return {
        "assertion": "admitted", "from_role": from_role, "to_role": to_role,
        "handoff_regions": handoff_regions,
        "recorded_admissions": [
            {"seq": r["seq"], "rule": r["payload"]["rule"],
             "to_region": r["payload"]["to_region"]}
            for r in admissions
        ],
        "unadmitted_regions": unadmitted,
        "holds": not unadmitted,
        "evidence": {"pure": True, "events": admissions},
        "note": (
            "every region this pair could hand content through has a "
            "recorded admission decision" if not unadmitted else
            "at least one region from_role can write and to_role can read "
            "has no recorded context_admit decision for this pair"
        ),
    }


@_tool
def create_concept_scw(
    concept: str,
    constitution: str = "",
    criterion: str = "",
    skills: Optional[list[str]] = None,
    max_iterations: int = 3,
) -> dict:
    """Build a Structured **Concept** Window: one concept, one maker/checker/judge
    formation, partitioned.

    The acronym does double duty on purpose. What makes a loop's shared context
    coherent is that all its roles work on ONE concept -- so the concept IS the
    shared context: readable by every role, writable by none, and what the judge
    grades against. A maker that specializes in producing X, a checker that
    specializes in checking X and a judge that specializes in judging X are one
    formation precisely because X is common to all three and private to none.

    Builds, in an order that is not cosmetic: a readonly `constitution`, a
    readonly `skills` region (the context-transfer operators this concept
    exposes), a `criterion` pinned before the judge binds to it, one
    `bridgeable=false` scratchpad per role, and one durable region per declared
    handoff. Grants are minted only along the topology -- no role can ever reach
    another role's pad, which is what makes declaring an exposure surface a
    requirement rather than a formality.

    This creates no runtime. An SCW is an architectural abstraction; an SCW
    runtime is one implementation of it. Whether a run achieved real isolation
    is measured afterwards by `isolation_level`, never asserted here.
    """
    try:
        result = cscw.build(_session.window, concept,
                            constitution=constitution, criterion_text=criterion,
                            skills=skills or [], max_iterations=max_iterations)
    except cscw.ConceptSCWError as exc:
        return {"ok": False, "error": "bad_formation", "message": str(exc)}
    result["suggested_gate_policies"] = cscw.gate_policies(result["plan"])
    return result
