"""Generate every distribution manifest from the one registry.

`distributions/` was nineteen files at 0.2.0 — eleven READMEs, four one-line
requirements files, two small JSON — describing what each distribution would
contain. This writes the manifests that actually install.

The reason it is generated rather than written is the reason `plugins/` is:
a plugin id that disagrees with the npm name that disagrees with the MCP server
name does not fail a test, it fails for a user, once, at install, with no
diagnostic. There is one declaration, in `maxey0_ss/distribution/registry.py`,
and everything else is derived from it.

    python scripts/build_distributions.py
    python scripts/build_distributions.py --check   # verify, write nothing

`--check` is invoked by `build_package.py` before anything is zipped, exactly as
`build_planes.py --check` is.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from maxey0_ss import __version__  # noqa: E402
from maxey0_ss.distribution import registry as reg  # noqa: E402

OUT = ROOT / "distributions"


# ---------------------------------------------------------------------------
# shared prose
# ---------------------------------------------------------------------------

GENERATED = (
    "<!-- Generated by scripts/build_distributions.py from "
    "maxey0_ss/distribution/registry.py. Edits here are overwritten. -->"
)


def _header(target: reg.Target) -> list[str]:
    status = {
        "shipped": "Installs from this repository.",
        "external": (
            "The artifact here is complete. Listing it is a platform action "
            "this repository cannot perform, and does not claim."
        ),
    }[target.status]
    lines = [
        GENERATED,
        "",
        f"# {target.title}",
        "",
        reg.ONE_LINE,
        "",
        f"**{status}**",
        "",
        "## Install",
        "",
        "```",
        target.install,
        "```",
        "",
    ]
    if target.optional_dependency:
        lines += [
            f"The `{target.optional_dependency}` package is an *optional* "
            f"dependency and is never vendored. The adapter imports it at the "
            f"moment it is used, so a build that does not use this harness does "
            f"not import it.",
            "",
        ]
    if target.notes:
        lines += [target.notes, ""]
    return lines


def _surface_table() -> list[str]:
    from maxey0_ss.mcp_surface import build_surface

    surface = build_surface()
    lines = [
        f"## The {len(surface.tools)} tools",
        "",
        "| tool | capability |",
        "|---|---|",
    ]
    for tool in surface.tools:
        lines.append(f"| `{tool.name}` | {tool.capability or 'public'} |")
    lines.append("")
    return lines


# ---------------------------------------------------------------------------
# builders
# ---------------------------------------------------------------------------


def readme(target: reg.Target) -> str:
    lines = _header(target)
    if target.kind in {"server", "connector", "app"}:
        lines += _surface_table()
    if target.artifacts:
        lines += ["## What this is", "", *(f"- `{a}`" for a in target.artifacts), ""]
    lines += [
        "## Identity",
        "",
        f"- product `{reg.PRODUCT}`",
        f"- MCP namespace `{reg.MCP_NAMESPACE}` — every tool and resource",
        f"- distribution id `{reg.DISTRIBUTION_ID}`",
        f"- version `{__version__}`",
        f"- protocol `{reg.MCP_PROTOCOL}`",
        "",
        f"See [the distribution matrix](../{'../' if '/' in target.generates[0].split('distributions/')[1].rsplit('/',1)[0] else ''}DISTRIBUTION_MATRIX.md).",
        "",
    ]
    return "\n".join(lines)


def harness_requirements(target: reg.Target) -> str:
    return (
        f"# Generated by scripts/build_distributions.py. Do not edit.\n"
        f"# Optional dependency for the {target.title} adapter.\n"
        f"# Never vendored and never imported unless the adapter is used: the\n"
        f"# adapter defers the import to the moment it is needed, so a build\n"
        f"# that does not use this harness does not carry it.\n"
        f"{target.optional_dependency}\n"
    )


def mcp_json(target: reg.Target) -> str:
    """A `.mcp.json` fragment naming this server."""
    if target.id == "mcp-stdio":
        server = {
            "command": "python",
            "args": ["-m", f"{reg.PYTHON_PACKAGE}.mcp_stdio_server"],
            "env": {"PYTHONUNBUFFERED": "1"},
        }
    else:
        server = {"type": "http", "url": reg.REMOTE_MCP_URL}
    return json.dumps({"mcpServers": {reg.MCP_NAMESPACE: server}}, indent=2) + "\n"


def connector_json(target: reg.Target) -> str:
    """A remote MCP connector descriptor."""
    return json.dumps(
        {
            "name": reg.MCP_NAMESPACE,
            "title": target.title,
            "description": reg.ONE_LINE,
            "version": __version__,
            "transport": {
                "type": "streamable-http",
                "url": reg.REMOTE_MCP_URL,
                "protocolVersion": reg.MCP_PROTOCOL,
            },
            "authentication": {
                "type": "bearer",
                "required": True,
                "note": (
                    "The edge forwards Authorization verbatim and terminates it "
                    "at the origin. The live origin rejects unauthenticated "
                    "tools/call with a role-'public' permission error; "
                    "maxey0-ss.auth.manifest reports admin_open only if "
                    "MAXEY0_AUTH_MODE=disabled without MAXEY0_PUBLIC=1."
                ),
            },
            "homepage": reg.HOMEPAGE,
            "license": reg.LICENSE,
            "publisher": reg.AUTHOR,
        },
        indent=2,
    ) + "\n"


def chatgpt_app_json(target: reg.Target) -> str:
    """A ChatGPT app manifest: an MCP server plus what the surface offers."""
    from maxey0_ss.mcp_surface import build_surface

    surface = build_surface()
    return json.dumps(
        {
            "schema_version": "v1",
            "name_for_human": target.title,
            "name_for_model": reg.MCP_NAMESPACE.replace("-", "_"),
            "description_for_human": reg.ONE_LINE,
            "description_for_model": (
                "Governed context and execution. Create and describe SCW "
                "windows, inspect the gate on an explicit SCW address, observe "
                "host-supplied context partitions, send gated model egress, and "
                "read the hash-chained containment record. Every tool call and "
                "every model egress is attributed to a window and attested."
            ),
            "version": __version__,
            "mcp": {
                "url": reg.REMOTE_MCP_URL,
                "protocol_version": reg.MCP_PROTOCOL,
                "tools": len(surface.tools),
                "resources": len(surface.resources),
            },
            "ui": {
                "resource_uri": "ui://maxey0-ss/super-space.html",
                "supports_inline_app": True,
            },
            "auth": {
                "type": "bearer",
                "note": (
                    "The live origin rejects unauthenticated tools/call with a "
                    "role-'public' permission error; bearer is required for "
                    "tool execution, not merely supported."
                ),
            },
            "contact_email": "support@maxey0.com",
            "legal_info_url": f"{reg.HOMEPAGE}/legal",
            "logo_url": f"{reg.HOMEPAGE}/logo.png",
        },
        indent=2,
    ) + "\n"


def openai_connector_json(target: reg.Target) -> str:
    """The shape an OpenAI MCP connector entry takes."""
    return json.dumps(
        {
            "type": "mcp",
            "server_label": reg.MCP_NAMESPACE,
            "server_url": reg.REMOTE_MCP_URL,
            "server_description": reg.ONE_LINE,
            "require_approval": "always",
            "_note": (
                "require_approval is 'always' on purpose. This surface creates "
                "and closes windows and sends model egress; a connector that "
                "does those silently defeats the point of the record."
            ),
        },
        indent=2,
    ) + "\n"


def codex_config_toml(target: reg.Target) -> str:
    return (
        "# Generated by scripts/build_distributions.py. Append to ~/.codex/config.toml\n"
        "#\n"
        "# Codex reads MCP servers from this file. The stdio entry point is the\n"
        "# same surface the HTTP transport serves -- one definition, two\n"
        "# transports, so a tool cannot exist in one and not the other.\n"
        "\n"
        f'[mcp_servers.{reg.MCP_NAMESPACE.replace("-", "_")}]\n'
        'command = "python"\n'
        f'args = ["-m", "{reg.PYTHON_PACKAGE}.mcp_stdio_server"]\n'
        "\n"
        f'[mcp_servers.{reg.MCP_NAMESPACE.replace("-", "_")}.env]\n'
        'PYTHONUNBUFFERED = "1"\n'
    )


def codex_agents_md(target: reg.Target) -> str:
    return "\n".join([
        GENERATED,
        "",
        f"# {reg.PRODUCT} in Codex",
        "",
        reg.ONE_LINE,
        "",
        "## What is available",
        "",
        f"Every tool is in the `{reg.MCP_NAMESPACE}` namespace. The ones that "
        "matter most in a coding session:",
        "",
        f"- `{reg.MCP_NAMESPACE}.scw.create` — open a window for a task, under a "
        "declared parent.",
        f"- `{reg.MCP_NAMESPACE}.scw.describe` — what windows exist and which are "
        "instantiated.",
        f"- `{reg.MCP_NAMESPACE}.gate.inspect` — what the gate would decide about "
        "an explicit address.",
        f"- `{reg.MCP_NAMESPACE}.evidence.attestations` — the containment record: "
        "what was attempted across a boundary, and the outcome.",
        f"- `{reg.MCP_NAMESPACE}.provider.complete` — model egress that is gated "
        "and recorded before it leaves.",
        "",
        "## The rule that matters",
        "",
        "An SCW identifier is application state, not a process. Tools that read "
        "host context require an explicit, enforceable address; a malformed one "
        "is refused rather than guessed at.",
        "",
    ])


def a2a_agent_card(target: reg.Target) -> str:
    from maxey0_ss.mcp_surface import build_surface

    surface = build_surface()
    return json.dumps(
        {
            "protocolVersion": "0.3.0",
            "name": reg.PRODUCT,
            "description": reg.ONE_LINE,
            "url": f"https://{reg.REMOTE_MCP_HOST}/v1/a2a",
            "preferredTransport": "JSONRPC",
            "version": __version__,
            "provider": {"organization": reg.AUTHOR["name"], "url": reg.HOMEPAGE},
            "documentationUrl": f"{reg.HOMEPAGE}/docs",
            "capabilities": {
                "streaming": False,
                "pushNotifications": False,
                "stateTransitionHistory": True,
            },
            "defaultInputModes": ["text/plain", "application/json"],
            "defaultOutputModes": ["application/json"],
            "skills": [
                {
                    "id": "scw-governance",
                    "name": "Governed context windows",
                    "description": (
                        "Open, describe and close explicit context windows, and "
                        "gate what crosses between them."
                    ),
                    "tags": ["context", "isolation", "governance"],
                },
                {
                    "id": "containment-evidence",
                    "name": "Containment evidence",
                    "description": (
                        "The hash-chained record of what was attempted across "
                        "every boundary, with a verifier a third party can run."
                    ),
                    "tags": ["observability", "audit", "evidence"],
                },
                {
                    "id": "gated-egress",
                    "name": "Gated model egress",
                    "description": (
                        "Model calls admitted by the gate and recorded before "
                        "they leave, with the prompt digested rather than stored."
                    ),
                    "tags": ["safety", "egress", "providers"],
                },
            ],
            "securitySchemes": {
                "bearer": {"type": "http", "scheme": "bearer"},
            },
            "_surface": {"tools": len(surface.tools), "resources": len(surface.resources)},
        },
        indent=2,
    ) + "\n"


def distribution_matrix(_: reg.Target | None = None) -> str:
    rows = [
        GENERATED, "",
        f"# {reg.PRODUCT} distribution matrix", "",
        f"Version `{__version__}` · MCP `{reg.MCP_PROTOCOL}`", "",
        reg.ONE_LINE, "",
        "| target | platform | kind | status | install |",
        "|---|---|---|---|---|",
    ]
    for t in reg.TARGETS:
        rows.append(
            f"| [`{t.id}`]({_dir_for(t)}/) | {t.platform} | {t.kind} | "
            f"{t.status} | `{t.install.splitlines()[0]}` |"
        )
    rows += [
        "",
        "## What the two statuses mean",
        "",
        "**shipped** — the artifact in this repository is the thing that "
        "installs. Run the command and it works.",
        "",
        "**external** — the artifact is complete and correct, and publication "
        "is a platform action this repository cannot perform: a marketplace "
        "review, an app submission. The manifest is real; the listing is not "
        "ours to claim, so it is not claimed.",
        "",
        "There is no third status. A target with no artifact does not appear "
        "here.",
        "",
        "## One declaration",
        "",
        "Every file under `distributions/` is generated by "
        "`scripts/build_distributions.py` from "
        "`maxey0_ss/distribution/registry.py`, and packaging refuses to run if "
        "they have drifted. A plugin id that disagrees with the package name "
        "that disagrees with the MCP server name does not fail a test — it "
        "fails for a user, once, at install, with no diagnostic.",
        "",
    ]
    return "\n".join(rows)


def _dir_for(target: reg.Target) -> str:
    return target.generates[0].split("distributions/")[1].rsplit("/", 1)[0]


BUILDERS = {
    "README.md": readme,
    "requirements.txt": harness_requirements,
    "mcp.json": mcp_json,
    "connector.json": connector_json,
    "app.json": chatgpt_app_json,
    "openai-connector.json": openai_connector_json,
    "config.toml": codex_config_toml,
    "AGENTS.md": codex_agents_md,
    "agent-card.json": a2a_agent_card,
}


def wanted() -> dict[Path, str]:
    """Every generated file and its exact content."""
    out: dict[Path, str] = {ROOT / "distributions" / "DISTRIBUTION_MATRIX.md": distribution_matrix()}
    for target in reg.TARGETS:
        for rel in target.generates:
            name = rel.rsplit("/", 1)[-1]
            builder = BUILDERS.get(name)
            if builder is None:
                raise SystemExit(f"no builder for {name!r} (target {target.id})")
            out[ROOT / rel] = builder(target)
    return out


def missing_artifacts() -> list[str]:
    """Every declared artifact that is not on disk.

    A row in the registry is a promise that a file exists and works. This is
    the half of that promise a script can check.
    """
    problems = []
    for target in reg.TARGETS:
        for rel in target.artifacts:
            if not (ROOT / rel).exists():
                problems.append(f"{target.id}: declared artifact missing: {rel}")
    return problems


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="verify, write nothing")
    args = ap.parse_args(argv)

    problems = missing_artifacts()
    files = wanted()

    if args.check:
        drift = [
            str(path.relative_to(ROOT).as_posix())
            for path, text in files.items()
            if not path.exists() or path.read_text(encoding="utf-8") != text
        ]
        existing = {
            p.relative_to(ROOT).as_posix()
            for p in OUT.rglob("*") if p.is_file()
        }
        orphans = sorted(existing - {p.relative_to(ROOT).as_posix() for p in files})
        for problem in problems:
            print(f"  {problem}")
        for d in sorted(drift):
            print(f"  drifted: {d}")
        for o in orphans:
            print(f"  orphan:  {o}")
        if problems or drift or orphans:
            print("\nrun: python scripts/build_distributions.py")
            return 1
        print(f"distributions: {len(files)} files match the registry, "
              f"{len(reg.TARGETS)} targets, every artifact present")
        return 0

    if problems:
        for problem in problems:
            print(f"  [FAIL] {problem}")
        return 1

    import shutil

    if OUT.exists():
        shutil.rmtree(OUT)
    for path, text in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    print(f"wrote {len(files)} files across {len(reg.TARGETS)} distribution targets")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
