"""Enforce docs/LEXICON.md across the repository.

A lexicon that is only written down is a style guide, and style guides lose. In
0.6.0 the same referent carried up to five names, `maxey0_*` tools lived on a
server called `worlds`, and three files listed the Studio's views three
different ways — all while every test passed, because nothing checked.

This checks. It runs inside `scripts/validate_plugin.py`, so a term that drifts
fails the same gate a broken import does.

    python scripts/check_lexicon.py
    python scripts/check_lexicon.py --verbose

What it enforces:

  1. No retired tool name survives outside the migration tables.
  2. Every catalog tool is registered by exactly one plane server.
  3. No tool name is `maxey0_`-prefixed — the prefix must name the plane.
  4. Every command file exists, and every command in the catalog has one.
  5. Every `allowed-tools` entry names a real tool on the right connector.
  6. Retired nouns do not appear in product copy.
  7. Every list of Studio views agrees with the catalog.

It deliberately does **not** check prose style. The failure mode being
prevented is two names for one thing, not an inelegant sentence.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "server"))
from planes import catalog  # noqa: E402

#: Files allowed to contain retired names, because naming them is their job.
MIGRATION_DOCS = {
    "docs/LEXICON.md",
    "skills/scw/reference/migration.md",
    "plugins/maxey0-context/skills/scw/reference/migration.md",
    "scripts/check_lexicon.py",
    "server/planes/catalog.py",
    "docs/ROADMAP.md",     # a changelog records what things used to be called
    "CHANGELOG.md",
}

#: Directories whose contents are data or generated by something else.
SKIP_DIRS = {
    ".git", "__pycache__", "vendor", "dist", "node_modules", ".smoke",
    ".claude", "experiments",
}

TEXT_SUFFIXES = {".md", ".py", ".json", ".js", ".html", ".css", ".ts", ".tsx"}

#: Nouns retired by LEXICON.md §2, with what to use instead. Matched as whole
#: words in product copy only — vendored skill titles are data, not copy.
RETIRED_NOUNS = {
    r"\bworlds?\b": "region / maxey0-context (the noun 'world' is retired)",
    r"\bStructured Concept Window\b": "Structured Context Window",
}

#: Where retired nouns are still legitimate.
NOUN_EXEMPT = MIGRATION_DOCS | {
    "server/planes/catalog.py",
    "server/maxey0_studio/static/index.html",   # the view is named Mission Control
    "server/maxey0_studio/static/studio.js",
    "server/maxey0_studio/mission.py",
    "server/maxey0_studio/app.py",
    "commands/studio.md",                       # lists the nine views verbatim
    "server/maxey0_studio/static/graph3d.js",   # "world space" is the graphics term
    "plugins/maxey0-observe/commands/studio.md",
}


def repo_files() -> list[Path]:
    out = []
    for p in ROOT.rglob("*"):
        if not p.is_file() or p.suffix not in TEXT_SUFFIXES:
            continue
        if any(part in SKIP_DIRS for part in p.relative_to(ROOT).parts):
            continue
        out.append(p)
    return sorted(out)


def rel(p: Path) -> str:
    return p.relative_to(ROOT).as_posix()


#: Where the lexicon governs: everything a user reads or types.
#:
#: It deliberately does not govern Python identifiers inside the runtime. The
#: vendored implementation keeps its own names — `server/vendor/` is generated
#: and must never be hand-edited — and `planes/bootstrap.register()` is the one
#: place a name is translated. That is what makes the lexicon a property of the
#: surface rather than a fork of the engine, so flagging `maxey0_concepts` where
#: it is a function object would be flagging the design working.
SURFACE_ROOTS = ("docs/", "commands/", "skills/", "agents/", "plugins/",
                 "hooks/", "ui/", "server/maxey0_studio/static/")
SURFACE_FILES = ("README.md", "manifest.json", "CHANGELOG.md")


def _is_surface(path: Path) -> bool:
    r = rel(path)
    parts = path.relative_to(ROOT).parts
    # A plugin's own `server/` is `scripts/build_planes.py`'s copy of the same
    # internal implementation that is exempt at the repository root -- copying
    # code so a plugin installs standalone does not turn it into product copy.
    # Its copy of the Studio's own UI text stays checked, same as the root's.
    if len(parts) > 2 and parts[0] == "plugins" and parts[2] == "server":
        return "maxey0_studio" in parts and "static" in parts
    return r.startswith(SURFACE_ROOTS) or r in SURFACE_FILES or r.endswith(
        (".claude-plugin/plugin.json", ".claude-plugin/marketplace.json"))


def check_retired_tools(files: list[Path]) -> list[str]:
    """Rule 1 and 3: no 0.6.0 tool name on the surface, no `maxey0_` tool prefix."""
    problems = []
    patterns = {
        # Not preceded or followed by a path separator: `server/maxey0_studio/`
        # is a directory this repository actually has, and a path segment that
        # happens to spell a retired tool name is not a use of that tool.
        legacy: re.compile(rf"(?<![\w./]){re.escape(legacy)}(?![\w/])")
        for legacy in catalog.RETIRED
        # `read` and `write` are ordinary English; they were retired as tool
        # names, and matching them as bare words would flag every sentence.
        if legacy not in {"read", "write", "promote"}
    }
    for path in files:
        if rel(path) in MIGRATION_DOCS or not _is_surface(path):
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        for legacy, pat in patterns.items():
            for m in pat.finditer(text):
                line = text[:m.start()].count("\n") + 1
                problems.append(
                    f"{rel(path)}:{line}  retired tool `{legacy}` "
                    f"-> `{catalog.RETIRED[legacy]}`"
                )
    return problems


def check_catalog_registered() -> list[str]:
    """Rule 2: every catalog tool is registered, by exactly one plane."""
    import asyncio

    problems = []
    for plane, module in (("context", "planes.context_plane"),
                          ("loops", "planes.loops_plane"),
                          ("observe", "planes.observe_plane")):
        mod = __import__(module, fromlist=["build"])
        registered = {t.name for t in asyncio.run(mod.build().list_tools())}
        expected = {t.name for t in catalog.BY_CONNECTOR[plane]}
        for missing in sorted(expected - registered):
            problems.append(f"{plane}: catalog declares `{missing}`, server does not register it")
        for extra in sorted(registered - expected):
            problems.append(f"{plane}: server registers `{extra}`, catalog does not declare it")
    for t in catalog.ALL:
        if t.name.startswith("maxey0_"):
            problems.append(f"`{t.name}` is maxey0_-prefixed; the prefix must name the plane")
    return problems


def check_commands() -> list[str]:
    """Rules 4 and 5: commands exist, and their allowed-tools are real."""
    problems = []
    conn = {t.name: catalog.CONNECTORS[t.connector]["connector"] for t in catalog.ALL}

    for name, plane, _ in catalog.COMMANDS:
        path = ROOT / "commands" / f"{name}.md"
        if not path.exists():
            problems.append(f"catalog declares /maxey0:{name}, commands/{name}.md is missing")
            continue
        text = path.read_text(encoding="utf-8")
        m = re.search(r"^allowed-tools:\s*(.+)$", text, re.M)
        if not m:
            problems.append(f"commands/{name}.md has no allowed-tools; the plugin UI "
                            f"then shows nothing for it")
            continue
        for entry in (e.strip() for e in m.group(1).split(",")):
            if not entry.startswith("mcp__"):
                continue          # Bash, Task and friends
            try:
                _, connector, tool = entry.split("__", 2)
            except ValueError:
                problems.append(f"commands/{name}.md: malformed allowed-tools entry {entry!r}")
                continue
            if tool not in catalog.BY_NAME:
                problems.append(f"commands/{name}.md: `{tool}` is not a catalog tool")
            elif conn[tool] != connector:
                problems.append(f"commands/{name}.md: `{tool}` is on `{conn[tool]}`, "
                                f"not `{connector}`")

    for path in sorted((ROOT / "commands").glob("*.md")):
        if path.stem not in {n for n, _, _ in catalog.COMMANDS}:
            problems.append(f"commands/{path.name} exists but the catalog does not declare it")
    return problems


def _is_generated_reference(path: Path) -> bool:
    """Concept reference files are rendered from the vendored manifest.

    Their prose is Maxey0 knowledge-base text, not product copy: a skill titled
    "Latent World Construction" keeps its name because renaming vendored data
    to satisfy a product lexicon would falsify the data. LEXICON.md 2 says the
    reasoning sense of "world" survives here and nowhere else.
    """
    parts = path.relative_to(ROOT).parts
    return "skills" in parts and "reference" in parts


def _unplugged(r: str) -> str:
    """Strip a `plugins/<name>/` prefix, so a plugin's own copy of an exempt
    root file (its `server/maxey0_studio/static/`) is recognized as the same
    file rather than a new path nobody exempted."""
    parts = r.split("/")
    if len(parts) > 2 and parts[0] == "plugins":
        return "/".join(parts[2:])
    return r


def check_nouns(files: list[Path]) -> list[str]:
    problems = []
    for path in files:
        if (rel(path) in NOUN_EXEMPT or _unplugged(rel(path)) in NOUN_EXEMPT
                or _is_generated_reference(path) or not _is_surface(path)):
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        for pattern, replacement in RETIRED_NOUNS.items():
            for m in re.finditer(pattern, text, re.I):
                line = text[:m.start()].count("\n") + 1
                problems.append(f"{rel(path)}:{line}  retired noun "
                                f"{m.group(0)!r} -> {replacement}")
    return problems


def check_views(files: list[Path]) -> list[str]:
    """Rule 7: any file that lists views lists the catalog's nine."""
    problems = []
    names = [n for n, _ in catalog.VIEWS]
    retired_views = {"SCW Window", "Semantic 3D", "Experiment"}
    for path in files:
        exempt = MIGRATION_DOCS | NOUN_EXEMPT
        if rel(path) in exempt or _unplugged(rel(path)) in exempt:
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        for view in retired_views:
            for m in re.finditer(rf"\*\*{re.escape(view)}\*\*", text):
                line = text[:m.start()].count("\n") + 1
                problems.append(f"{rel(path)}:{line}  retired Studio view "
                                f"{view!r}; the nine are {', '.join(names)}")
    return problems


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--verbose", action="store_true")
    args = ap.parse_args()

    files = repo_files()
    checks = [
        ("retired tool names", check_retired_tools(files)),
        ("catalog vs registered", check_catalog_registered()),
        ("commands and allowed-tools", check_commands()),
        ("retired nouns", check_nouns(files)),
        ("Studio views", check_views(files)),
    ]

    total = 0
    for label, problems in checks:
        if problems:
            total += len(problems)
            print(f"\n{label}: {len(problems)} problem(s)")
            for p in problems[:40]:
                print(f"  {p}")
            if len(problems) > 40:
                print(f"  ... and {len(problems) - 40} more")
        elif args.verbose:
            print(f"{label}: ok")

    counts = catalog.counts()
    if total:
        print(f"\nLEXICON: {total} problem(s). See docs/LEXICON.md.")
        return 1
    print(f"LEXICON: clean across {len(files)} files "
          f"({counts['total']} tools: {counts['context']} context, "
          f"{counts['loops']} loops, {counts['observe']} observe)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
