"""Generate the TypeScript surface from `server/planes/catalog.py`.

The catalog is the single source of truth for what the product registers. The
front end has to agree with it, and the way that agreement usually rots is that
someone renames a tool in Python and the TypeScript keeps compiling against the
old name because nothing connects them.

So the connection is a build step rather than a convention: this script emits
`ui/src/generated/catalog.ts`, `tsc` type-checks every use of it, and
`npm run check` fails when a name no longer exists. A rename in Python becomes
a compile error in TypeScript, which is the only kind of agreement that holds.

    python scripts/generate_ui_types.py
    python scripts/generate_ui_types.py --check   # verify, write nothing

The file it writes is committed. A generated file that is not committed is a
file nobody reviews.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "server"))
from planes import catalog  # noqa: E402

TARGET = ROOT / "ui" / "src" / "generated" / "catalog.ts"


def ts_string(value: str) -> str:
    return json.dumps(value)


def render() -> str:
    lines = [
        "// GENERATED by scripts/generate_ui_types.py — do not edit.",
        "//",
        "// The source of truth is server/planes/catalog.py. Rename a tool there",
        "// and every use of the old name here becomes a compile error, which is",
        "// the point: a front end that agrees with the backend by convention",
        "// stops agreeing the first time someone is in a hurry.",
        "",
        "/** What the system IS. Maxey0 owns two of the three. */",
        "export type PlaneId = 'execution' | 'context' | 'engineering';",
        "",
        "/** What INSTALLS. Many-to-one onto planes; Execution has none. */",
        "export type ConnectorId = 'context' | 'loops' | 'observe';",
        "",
        "export interface PlaneMeta {",
        "  readonly title: string;",
        "  readonly owner: string;",
        "  readonly holds: string;",
        "  readonly maxey0: string;",
        "  /** Empty for Execution: Maxey0 does not own that plane. */",
        "  readonly connectors: string;",
        "}",
        "",
        "export interface ConnectorMeta {",
        "  readonly connector: string;",
        "  readonly plane: PlaneId;",
        "  readonly title: string;",
        "  readonly tagline: string;",
        "  readonly owns: string;",
        "  readonly alone: string;",
        "}",
        "",
        "export interface ToolMeta {",
        "  readonly name: ToolName;",
        "  readonly connector: ConnectorId;",
        "  readonly group: string;",
        "  readonly summary: string;",
        "  /** true when the tool changes state the ledger records. */",
        "  readonly mutates: boolean;",
        "}",
        "",
        "export const PLANES: Readonly<Record<PlaneId, PlaneMeta>> = {",
    ]
    for pid in ("execution", "context", "engineering"):
        meta = catalog.PLANES[pid]
        lines.append(f"  {pid}: {{")
        for key in ("title", "owner", "holds", "maxey0", "connectors"):
            lines.append(f"    {key}: {ts_string(meta[key])},")
        lines.append("  },")
    lines.append("} as const;")
    lines.append("")

    lines.append("export const CONNECTORS: Readonly<Record<ConnectorId, ConnectorMeta>> = {")
    for cid in ("context", "loops", "observe"):
        meta = catalog.CONNECTORS[cid]
        lines.append(f"  {cid}: {{")
        for key in ("connector", "plane", "title", "tagline", "owns", "alone"):
            lines.append(f"    {key}: {ts_string(meta[key])},")
        lines.append("  },")
    lines.append("} as const;")
    lines.append("")

    lines.append("export type ToolName =")
    for tool in catalog.ALL:
        lines.append(f"  | {ts_string(tool.name)}")
    lines[-1] = lines[-1] + ";"
    lines.append("")

    lines.append("export const TOOLS: readonly ToolMeta[] = [")
    for tool in catalog.ALL:
        lines.append(
            "  { name: %s, connector: %s, group: %s, summary: %s, mutates: %s },"
            % (ts_string(tool.name), ts_string(tool.connector), ts_string(tool.group),
               ts_string(tool.summary), "true" if tool.mutates else "false")
        )
    lines.append("] as const;")
    lines.append("")

    lines.append("/** The nine Studio views, named once, in server/planes/catalog.py. */")
    lines.append("export const VIEWS: readonly { id: string; name: string; shows: string }[] = [")
    for name, shows in catalog.VIEWS:
        vid = name.lower().replace(" ", "-")
        lines.append(f"  {{ id: {ts_string(vid)}, name: {ts_string(name)}, "
                     f"shows: {ts_string(shows)} }},")
    lines.append("] as const;")
    lines.append("")

    counts = catalog.counts()
    lines.append("/** Computed from the catalog. Never write these down by hand. */")
    lines.append("export const COUNTS = {")
    for key in ("context", "loops", "observe", "total"):
        lines.append(f"  {key}: {counts[key]},")
    lines.append("} as const;")
    lines.append("")

    lines.append("export function toolsFor(connector: ConnectorId): readonly ToolMeta[] {")
    lines.append("  return TOOLS.filter((t) => t.connector === connector);")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    text = render()
    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else None
        if current != text:
            print(f"{TARGET.relative_to(ROOT).as_posix()} has drifted from the catalog")
            print("run: python scripts/generate_ui_types.py")
            return 1
        print(f"ui types: {len(catalog.ALL)} tools, generated file matches the catalog")
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(text, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT).as_posix()} "
          f"({len(catalog.ALL)} tools, {len(catalog.VIEWS)} views)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
